### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by nigoshh** [Rsl1122/ROM-tools#2]
Repository downloaded: 3/5/2018, 12:19 (UTC+3)

Your program is really advanced compared to what I have done in school until now; probably my comments won't prove extremely useful to you. One test failed, though, and in the end I wrote a suggestion to fix that.

# Style

I really like your code's style. It's easy to read, very well documented and commented; even if this level is too advanced for me to understand everything, it was easy to get a grip of each class's function.

Your use of empty lines helps to understand the code's structure. For example in the MainNavigation class's constructor you used empty lines to separate groups of three equal operations, performed on three different buttons.

I also like that you don’t care about going over that vertical layout line, and you sometimes write very long lines (for example in ToolsView). After all the computer screen is quite large, so it makes sense to use it all (as long as a line fits into it and you can read everything without scrolling). I noticed that it's easier to make sense of the code structure if you don't break lines.

I like that you wrote some (final) variable names in all caps instead of using camel case; it highlights that those variables are final, and they actually have a function similar to enums.

# Interfaces and inheritance

You used interfaces and inheritance very well. I like that Frontend is an interface, so you can easily implement another Frontend if you want, without changing the rest of the code (thanks to the State class).
Great examples of inheritance are the class Table, and all the classes that extend it.

# Single responsibility principle

Your program has a lot of classes. It isn't only because it is quite complex, but also because you employed very well the single responsibility principle, making very specialized classes. In particular it was interesting to see how you implemented the DAO design pattern in a different way than what we saw in the tikape course. You made a class for each SQL table, and even a static class inside those classes, for the column names. And then you used methods to construct SQL statements/queries, instead of writing them manually (for example method TableSQLParser in class FileTable). I didn’t understand why you would need all that at first. But then I realized that it might be very useful; in case you want to change a column name, you'd only have to change that in one place. For the same reason there also many enums, like in Views and Settings.

# Private constructors

I noticed that you wrote a private constructor for some classes (for example FileProcesses). These classes only contain information, like methods (for example FileProcesses) or final variables (for example style Strings in class Style); no instance of these classes is needed in the program. I don't know if hiding the constructor serves a practical purpose (security?), but at least it looks cool.

# Your own exceptions

Many things were interesting and new for a beginner like me. For example, I was amused that you can create your own customized exceptions, like your BackendException. I also like that you explain in Javadoc why exceptions could occur in a given method.

# Other cool stuff

I like that you often use functional style, like in ExceptionHandler, MainProcesses, FatalErrorScene and State. I've just finished a Haskell course, therefore I look forward to understanding how to integrate that magical stuff into non-functional languages like Java.

I also like that you utilized concurrency, creating a pool of 10 threads in Main. This way you can maintain the UI responsive even if some processes are doing heavy work in the background.

# Testing

You tested thoroughly every package (excluding frontend stuff). It's Interesting that you made some methods specifically for testing (like some setters in Main). I had wondered myself, when writing tests for my app: does it make sense to write extra stuff into the source code only for testing? Like making new methods, or changing a variable from final to not final. Apparently it does make sense, especially if they are only small methods like getters and setters.

You also mocked dependencies very well. Like the rest of your code, this is well organized, since you put all the fake classes into a separate package, utils.fakeClasses.

# MD5CheckSumTest failed!

This test was the only one that failed. I was almost happy because I had no idea how to suggest any improvement for your code otherwise.

You present two different hash values, one for Windows, and the other one for other operating systems. But I'm on Windows, and still I got the other value, so the test failed.

The hash value should be only one. According to [this](https://stackoverflow.com/questions/12289480/md5sum-different-on-linux-and-windows) and other sources, the different hashes for text files might result from how different operating systems implement line changes (with different unicode characters). But in MD5CheckSum you use FileInputStream, which reads a file as a byte stream, so probably the outcome depends only on which system you created (or modified) the text file on.

So I think you should only include one hash in this test, and that wouldn't fail on any OS.

**Comment by Rsl1122** [comment]
Thank you for the very throughout review, I appreciate the effort you've put into writing this.

### Interfaces

I love interfaces! I just recently discovered what all you can do with them in Java.  
Mainly the most interesting thing I find are [Functional interfaces](https://www.geeksforgeeks.org/functional-interfaces-java/), because they can be used to abstract so many things into lambdas (`() -> doStuff();` & `state -> doStuffTo(state)`) and method references (`object::referencedMethod`).

For example I realized that it is possible to give methods as parameters - Just like in JavaScript and python, albeit a bit more secure in terms of type. (This is done in this project via `MethodReference`-interfaces) 

It's a whole new way of reducing copy-paste code with a slight reduction of performance, for example in [FileProcesses](https://github.com/Rsl1122/ROM-tools/blob/master/Rom-tools/src/main/java/com/djrapitops/rom/backend/processes/FileProcesses.java#L143) passing a method to `performSingleFolderOperation` and `performAnOperationOnFiles`.
Previously the files for loop was present in all four methods

Another really useful way of using interfaces is to just write a new method in an interface, continue work on other code using the new method and worry about implementation of the new method later.
It reduces context switching a lot, so coding larger complexes requires less effort.

### Single Responsibility Principle

Nice to know that the principle is applied in some of the codebase.
I read this quote once that has really helped write more maintainable code.

> Don't write code that is easy to build onto, write code that is easy to delete.

I don't remember where I read it from but I think it was in [Clean Code-book](https://www.investigatii.md/uploads/resurse/Clean_Code.pdf) and that one really stuck with me.
It is easy to add and add, but then when you want to refactor something - "oh, removing this one bit causes changes in 45 different files and I can't keep them all in my head."

That happened to me once (not with this project) and it took a week to get the program to function again after the refactoring - I don't want it to happen again.

### Private constructors

This is a bit odd, but I'm only doing it because SonarCloud bugs out every time there is a class with all static methods.

I find that it is an anti-pattern to write a lot of classes with a lot of static only methods. Since Java is Object-oriented it would make more sense to write objects that handle specific actions instead.

For example in an older project of mine I have a class called PlaylistFileManager, and it only has static methods. With a name like that you'd think it would be given a file in the constructor and then it would have methods to manipulate that single file, but now an outside object calls the methods with a specific file. It is not optimal.

#### TableSQLParser

This class is actually copied from another project of mine that supports both SQLite and MySQL.
The original purpose of the class was thus make it easier to read the create table statements since MySQL and SQLite have different syntax for defining primary keys. Now it just reduces the amount of raw SQL I need to write :3

### Custom exceptions

Exception handling is still something am still I struggling with, but learning.
It's difficult to get proper error messages to the user - but alas! Custom exceptions come to the rescue, now a single catch clause can set a custom message for the user to see!

I've used non-runtime exceptions in the past (If you throw such exception you'll have to write throws to every method or catch it down the line - One example of these is IOException), but I find that this way the exceptions will be caught everywhere around the codebase, leaving try catch blocks all over the place & making it quite impossible to get all of them "fixed" in the eyes of a user.

runtime exceptions (For example IllegalStateException) seem like a really nice way of "stopping execution as soon as possible when error occurs" and it cleans up the code because there isn't a need for a bunch of try catch blocks every time you call a method. Hard part is actually remembering what methods might throw the runtime exceptions (It's why I write them in the Javadoc!).

Custom exceptions are also useful when using libraries that you might want to change later - Just wrap the library's exception to your own exception and then it can be changed later (Easy to delete). I've used this for the SQLDatabase, wrapping all SQLExceptions to a BackendException

### Setters for tests

I think this is another anti-pattern, but I find it easier to do it this way than by setting the variable accessible and changing the value via reflection. It probably matters more in larger projects and ones where the methods are supposed to be used as an API (Like libraries).

It probably makes more sense having the variable be package-private and placing the tests in the same package - so that the variable can be set there. Thanks for bringing this up, I'll have to look into it.

### MD5 test

This one is actually pretty tricky!  
It indeed is caused by line breaks being different on different OS:es, and that causes the checksum to be different.
I'm guessing I should use a non-text file for the test instead. Thanks!

### Summary

Thank you so much for your review. I found it very useful. (Sorry for rambling, but I like doing that sometimes)

I really recommend reading [Clean Code](https://www.investigatii.md/uploads/resurse/Clean_Code.pdf) book, it's free and you can read few pages every now and then. It drastically improved how I code. A lot of the stuff I mentioned here was learned from the book :)

**Comment by nigoshh** [comment]
Thanks a lot for all these tips! There's a lot to learn :D I'll check out the book.

Have a great summer!

**Comment by Rsl1122** [comment]
Thanks!

Have a nice summer as well :)
